package main

import (
	"embed"
	"io/fs"
	"log"
	"net/http"

	"github.com/jritsema/gotoolbox"
	"github.com/jritsema/gotoolbox/web"
)

//go:embed nextjs/dist
//go:embed nextjs/dist/_next
//go:embed nextjs/dist/_next/static/chunks/pages/*.js
//go:embed nextjs/dist/_next/static/*/*.js
var nextFS embed.FS

func main() {

	//Root at the `dist` folder generated by the Next.js app
	distFS, err := fs.Sub(nextFS, "nextjs/dist")
	if err != nil {
		log.Fatal(err)
	}

	mux := http.NewServeMux()

	//the static next.js app will be served under `/`
	mux.Handle("/", http.FileServer(http.FS(distFS)))

	//health check
	mux.Handle("/health", web.Action(healthcheck))

	//the API will be served under `/api`
	mux.Handle("/api/items", web.Action(itemsAPI))
	mux.Handle("/api/items/", web.Action(itemsAPI))

	//start http server
	env := gotoolbox.GetEnvWithDefault("PORT", "8080")
	log.Printf("Starting HTTP server at http://localhost:%v ...", env)
	log.Fatal(http.ListenAndServe(":"+env, mux))
}
